### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by Surfoo** [hoshsadiq/m3ufilter#16]
Hello,

I had a panic with the master branch (go 1.13.8):

```
go run cmd/m3u-filter/main.go -config=config.yaml

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/hoshsadiq/m3ufilter/logger.Get.func1(0xc0000984b0, 0x0, 0x83f49f, 0x3, 0xb7a0c0)
	/home/user/git/m3ufilter/logger/logger.go:21 +0x314
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc000098320, 0xc0000e8070, 0x30, 0x7f9220, 0xc0000e6401, 0xc0000815c0, 0xc00009f9f0)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/text_formatter.go:133 +0x53b
github.com/sirupsen/logrus.(*Entry).write(0xc0000e8070)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:255 +0xa1
github.com/sirupsen/logrus.Entry.log(0xc000097180, 0xc000081590, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:231 +0x19d
github.com/sirupsen/logrus.(*Entry).Log(0xc0000e8000, 0x4, 0xc00009fc10, 0x1, 0x1)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000e8000, 0xc000000004, 0x848ea5, 0x1d, 0xc00009fdb8, 0x2, 0x2)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 +0xe2
github.com/sirupsen/logrus.(*Logger).Logf(0xc000097180, 0x4, 0x848ea5, 0x1d, 0xc00009fdb8, 0x2, 0x2)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:145 +0x94
github.com/sirupsen/logrus.(*Logger).Infof(...)
	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:159
github.com/hoshsadiq/m3ufilter/m3u.GetPlaylist(0xc000081350, 0xb790c8, 0x0, 0x0, 0x4e8200)
	/home/user/git/m3ufilter/m3u/process.go:35 +0x22e
main.run(0x7ffded7c860d, 0xb, 0xc000010018, 0xc000010020)
	/home/user/git/m3ufilter/cmd/m3u-filter/main.go:42 +0x11e
main.main()
	/home/user/git/m3ufilter/cmd/m3u-filter/main.go:31 +0x26b
exit status 2
```

Println for some variables:
```
go run cmd/m3u-filter/main.go -config=config.yaml

f.File: /home/user/git/m3ufilter/m3u/process.go
basePkg: github.com/hoshsadiq/m3ufilter
strings.Split: [/home/user/git/m3ufilter/m3u/process.go]
```

**Comment by Surfoo** [comment]
fixed with the PR #18
